INSERT INTO tProduct (ProductID, ProductName, Colour, ReorderPoint) VALUES ('prod1', 'Kitchen Bottle Cap', 'Metallic Silver', 50);
INSERT INTO tProduct (ProductID, ProductName, Colour, ReorderPoint) VALUES ('prod2', 'Elegant Glass Vessel', 'Rustic Golden', 100);
INSERT INTO tProduct (ProductID, ProductName, Colour, ReorderPoint) VALUES ('prod3', 'Compact Plastic Flask', 'Bright Copper', 25);
INSERT INTO tProduct (ProductID, ProductName, Colour, ReorderPoint) VALUES ('prod4', 'Vintage Steel Kettle', 'Soft Silver', 75);
INSERT INTO tProduct (ProductID, ProductName, Colour, ReorderPoint) VALUES ('prod5', 'Ergonomic Polypropylene Mug', 'Matte Bronze', 80);
INSERT INTO tProduct (ProductID, ProductName, Colour, ReorderPoint) VALUES ('prod6', 'Stylish Ceramic Tumbler', 'Polished Steel', 40);
INSERT INTO tProduct (ProductID, ProductName, Colour, ReorderPoint) VALUES ('prod7', 'Innovative PET Fluid container', 'Tumbled Golden', 60);
INSERT INTO tProduct (ProductID, ProductName, Colour, ReorderPoint) VALUES ('prod8', 'Handcrafted Ceramic Tea Set', 'Brushed Nickel', 90);
INSERT INTO tProduct (ProductID, ProductName, Colour, ReorderPoint) VALUES ('prod9', 'Practical Plastic Bottle', 'Mirror Finish', 30);
INSERT INTO tProduct (ProductID, ProductName, Colour, ReorderPoint) VALUES ('prod10', 'Luxurious Silverwar Box', 'Antique Golden', 120);
INSERT INTO tProduct (ProductID, ProductName, Colour, ReorderPoint) VALUES ('prod11', 'Functional Silicone Food Cover', 'Matte Black', 85);
INSERT INTO tProduct (ProductID, ProductName, Colour, ReorderPoint) VALUES ('prod12', 'Attractive Porcelain Mug', 'Polished Copper', 95);
INSERT INTO tProduct (ProductID, ProductName, Colour, ReorderPoint) VALUES ('prod13', 'Practical Plastic Glass Holder', 'Bright Silver', 70);
INSERT INTO tProduct (ProductID, ProductName, Colour, ReorderPoint) VALUES ('prod14', 'Vintage Enamel Flask', 'Matte Bronze', 110);
INSERT INTO tProduct (ProductID, ProductName, Colour, ReorderPoint) VALUES ('prod15', 'Innovative Ceramic Tea Pot', 'Tumbled Golden', 65);
INSERT INTO tProduct (ProductID, ProductName, Colour, ReorderPoint) VALUES ('prod16', 'Handcrafted Wooden Spoon Set', 'Brushed Nickel', 80);
INSERT INTO tProduct (ProductID, ProductName, Colour, ReorderPoint) VALUES ('prod17', 'Practical Metallic Pencil Case', 'Mirror Finish', 45);
INSERT INTO tProduct (ProductID, ProductName, Colour, ReorderPoint) VALUES ('prod18', 'Luxurious Linen Bean Bag', 'Antique Golden', 100);
INSERT INTO tProduct (ProductID, ProductName, Colour, ReorderPoint) VALUES ('prod19', 'Functional Silicone Phone Case', 'Matte Black', 90);
INSERT INTO tProduct (ProductID, ProductName, Colour, ReorderPoint) VALUES ('prod20', 'Attractive Ceramic Mug', 'Polished Copper', 95);
INSERT INTO tProduct (ProductID, ProductName, Colour, ReorderPoint) VALUES ('prod21', 'Practical Plastic Grocery Bag', 'Bright Silver', 75);
INSERT INTO tProduct (ProductID, ProductName, Colour, ReorderPoint) VALUES ('prod22', 'Vintage Enamel Jar', 'Matte Bronze', 120);
INSERT INTO tProduct (ProductID, ProductName, Colour, ReorderPoint) VALUES ('prod23', 'Innovative Ceramic Tea Setting', 'Tumbled Golden', 65);
INSERT INTO tProduct (ProductID, ProductName, Colour, ReorderPoint) VALUES ('prod24', 'Handcrafted Wooden Pencil Box', 'Brushed Nickel', 80);
INSERT INTO tProduct (ProductID, ProductName, Colour, ReorderPoint) VALUES ('prod25', 'Practical Metallic Ruler', 'Mirror Finish', 45);
INSERT INTO tProduct (ProductID, ProductName, Colour, ReorderPoint) VALUES ('prod26', 'Luxurious Linen Towel Set', 'Antique Golden', 100);
INSERT INTO tProduct (ProductID, ProductName, Colour, ReorderPoint) VALUES ('prod27', 'Functional Silicone Flask', 'Matte Black', 90);
INSERT INTO tProduct (ProductID, ProductName, Colour, ReorderPoint) VALUES ('prod28', 'Attractive Ceramic Vase', 'Polished Copper', 95);
INSERT INTO tProduct (ProductID, ProductName, Colour, ReorderPoint) VALUES ('prod29', 'Practical Plastic Toothbrush Holder', 'Bright Silver', 75);
INSERT INTO tProduct (ProductID, ProductName, Colour, ReorderPoint) VALUES ('prod30', 'Vintage Enamel Mug', 'Matte Bronze', 120);
